apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "192.168.5.240"
    hostnames:
    - "hostname240"
  - ip: "192.168.5.241"
    hostnames:
    - "hostname241"
  - ip: "192.168.5.242"
    hostnames:
    - "hostname242"
  - ip: "192.168.5.243"
    hostnames:
    - "hostname243"
  containers:
  - args:
    volumeMounts:
    - mountPath: /opt/spark/work-dir
      name: workdata
      readOnly: false
  serviceAccountName: sparkuser1
  volumes:
  - name: workdata
    persistentVolumeClaim:
      claimName: spark-pvc-workdata0