apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "192.168.5.240"
    hostnames:
    - "192-168-5-240.kydsj.com"
  - ip: "192.168.5.241"
    hostnames:
    - "192-168-5-241.kydsj.com"
  - ip: "192.168.5.242"
    hostnames:
    - "192-168-5-242.kydsj.com"
  - ip: "192.168.5.243"
    hostnames:
    - "192-168-5-243.kydsj.com"
  containers:
  - args:
    volumeMounts:
    - mountPath: /mnt
      name: workdata
      readOnly: false
  serviceAccountName: sparkuser1
  volumes:
  - name: workdata
    persistentVolumeClaim:
      claimName: spark-pvc-workdata0